### ISSUE TITLE
Missing method call to actually build the thing

### ISSUE THREAD

**Issue by fj-ar** [RaulBejarano/Ultimate-Toroidal-Propeller-Generator#18]
Missing toroidal_propeller(); in the end of the file.

**Comment by Little-Night-Wolf** [comment]
Please show where is missing or where should I put to export.

**Comment by RaulBejarano** [comment]
Hello @fj-ar. Thank you for your interest in the project. At first the file "src/toroidal_propeller.scad" is intended to be a simple library to import into the designer's scad. Do you think it would simplify the use of the project to include the module call in the toroidal_propeller.scad file? If so, I invite you to include it yourself and make a pull request so that you appear as a contributor

**Comment by Little-Night-Wolf** [comment]
I've made the pull request by adding the "toroidal helix();" and other things that I find interesting

**Comment by fj-ar** [comment]
I used scad for the first time in my life, as probably many others will who stumble upon this project. So I think it would make sense to include the execution in the script!
